/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on 05/05/2013, 21:16:26
 */
package gui;

import Sistema.ContadorDePalavrasJava;
import Sistema.InteressadoNoContadorDePalavrasJava;
import javax.swing.SpinnerListModel;

/**
 *
 * @author Lurian
 */
public class MainFrame extends javax.swing.JFrame implements InteressadoNoContadorDePalavrasJava{
    
    
    private ContadorDePalavrasJava contador = ContadorDePalavrasJava.getInstance();

    /** Creates new form MainFrame */
    public MainFrame() {
        contador.adicionaNovoInteressadoNoContador(this);

        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        PalavrasJavaTable = new javax.swing.JTable();
        TituloLabel = new javax.swing.JLabel();
        DiretorioLabel = new javax.swing.JLabel();
        DiretorioTextField = new javax.swing.JTextField();
        NumeroThreadLabel = new javax.swing.JLabel();
        NumeroThreadSpinner = new javax.swing.JSpinner();
        ProgressoBar = new javax.swing.JProgressBar();
        ProgressoLabel = new javax.swing.JLabel();
        ContarButton = new javax.swing.JButton();
        TempoGastoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PalavrasJavaTable.setModel(new PalavrasJavaTableModel());
        jScrollPane1.setViewportView(PalavrasJavaTable);

        TituloLabel.setFont(new java.awt.Font("Tahoma", 1, 24));
        TituloLabel.setText("Contador de Palavras Java");

        DiretorioLabel.setText("Diretorio a ser Contado:");

        DiretorioTextField.setAutoscrolls(false);

        NumeroThreadLabel.setText("Numero de Threads Utilizadas:");

        NumeroThreadSpinner.setModel(new SpinnerListModel(new Integer[]{0,1,2,3,4,5}));

        ProgressoBar.setStringPainted(true);

        ProgressoLabel.setText("Progresso:");

        ContarButton.setText("Analisar");
        ContarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContarButtonActionPerformed(evt);
            }
        });

        TempoGastoLabel.setText("Tempo Gasto na Ultima Contagem:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TempoGastoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NumeroThreadLabel)
                                .addGap(15, 15, 15)
                                .addComponent(NumeroThreadSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(328, 328, 328))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(ProgressoLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(ProgressoBar, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE))
                                    .addComponent(TituloLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(DiretorioLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(DiretorioTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(ContarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(TituloLabel)
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DiretorioLabel)
                            .addComponent(DiretorioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NumeroThreadLabel)
                            .addComponent(NumeroThreadSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ProgressoBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ProgressoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(TempoGastoLabel)
                        .addGap(32, 32, 32)
                        .addComponent(ContarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void ContarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContarButtonActionPerformed
    String dir = DiretorioTextField.getText();
    int numeroDeThreads = (Integer) NumeroThreadSpinner.getValue();
    
    ProgressoBar.setValue(0);
    
    
    
    contador.contaPalavrasJava(dir, numeroDeThreads);
}//GEN-LAST:event_ContarButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ContarButton;
    private javax.swing.JLabel DiretorioLabel;
    private javax.swing.JTextField DiretorioTextField;
    private javax.swing.JLabel NumeroThreadLabel;
    private javax.swing.JSpinner NumeroThreadSpinner;
    private javax.swing.JTable PalavrasJavaTable;
    private javax.swing.JProgressBar ProgressoBar;
    private javax.swing.JLabel ProgressoLabel;
    private javax.swing.JLabel TempoGastoLabel;
    private javax.swing.JLabel TituloLabel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public synchronized void avisaNumeroDeArquivos(int numeroDeArquivos) {
        ProgressoBar.setMaximum(numeroDeArquivos);
    }

    @Override
    public synchronized void avisaAtualizacaoDoContador() {
        int novoValor = ProgressoBar.getValue() + 1;
        ProgressoBar.setValue(novoValor);
        ProgressoBar.setString(ProgressoBar.getValue() + " arquivos processados de " + ProgressoBar.getMaximum() + " achados" );
        
        PalavrasJavaTable.updateUI();
    }

    @Override
    public synchronized void avisaTerminoDaContagem(long tempoGasto) {
        TempoGastoLabel.setText("Tempo Gasto na Ultima Contagem: " + tempoGasto + " ms");
      
    }
}
